### ISSUE TITLE
Inspirations and little thoughts on this WIP plugin

### ISSUE THREAD

**Issue by LeCheenaX** [Leonezz/tasks-timeline-view#5]
Dear contibutor, 

I am new to your plugin Tasks Calendar Wrapper. However I was using similar plugins (actually not plugins but css) named Tasks Timeline and Tasks Calendar: https://github.com/702573N/Obsidian-Tasks-Timeline/

These plugins were quite useful for me but not convenient enough to satisfy my goal.  They only manifest To-Dos created in daily notes or designated folder, so if I create a To-Do in my project folder, it will not be listed in daily timeline unless I manually due a date with tasks plugin. 

I modified the css and js file to allow these fake plugins to collect incompleted tasks in all folders with exclusions,  as Un-scheduled page manifests in the attached screenshot. 
![image](https://github.com/Leonezz/tasks-timeline-view/assets/102142515/79e4cfb4-e739-448c-8657-be56bcbc06b2)

I also created another page named Inbox for my plans that are important but hard to give a schedule. 
![image](https://github.com/Leonezz/tasks-timeline-view/assets/102142515/854cbc4d-661d-41fa-8e5f-bb42264708df)

Fortunately, I found your plugin just few days ago, which is keep updating(previous 2 plugins are abandoned for 2 years), I also noticed that in the main.js there are over 50 times of the code lines compared to the previous plugins. And this plugin indeed saves me a lot work to modify the js file for more features. 

But there is also an ungraceful moment, for example, all unplanned tasks will be listed under Today panel, but if I had a task scheduled tomorrow, it will be overwhlemed by the unplanned tasks. Thus, it would be greate to place the unplanned tasks at the bottom of the plugin, with a new title "UnDated" to subsitute for the date of today. 
![image](https://github.com/Leonezz/tasks-timeline-view/assets/102142515/2905c6c7-1ae0-4d17-8468-b28815ee47c3)
 

Very honorable to you for developping this plugin!

**Comment by LeCheenaX** [comment]
This issue can be resolved by clicking the 'Todo' Panel under Focus On Today, but it would still be great to re-array the position of overdue and undated tasks, from today panel to another individual panel like 'To be dated', and stick them at the bottom. Trying to resolve this myself.

**Comment by Leonezz** [comment]
Hi @LeCheenaX thanks for your attention to this project and the valuable experiences and ideas you are sharing. I will see how these can be implemented in this grand new project and try to get it online soon. (ps. I am now an employed man instead of a student, so I cannot put as much time on this as before, thus it will be quite some time before you can really see the release coming, sorry in advance.)

**Comment by CuteWaterBeary** [comment]
@LeCheenaX you can fix this by changing the css to make it hide the undated tasks when you select that instead of focus on them. Replace the bottom section of styles.css labeled Filter with 

```css

/* Filter */
/* .taskido.todoFilter
	.year:not([data-types~="due"]):not([data-types~="scheduled"]):not(
		[data-types~="process"]
	):not([data-types~="start"]) {
	display: none;
}

.taskido.todoFilter
	.details:not([data-types~="due"]):not([data-types~="scheduled"]):not(
		[data-types~="process"]
	):not([data-types~="start"]) {
	display: none;
} */

.taskido.todoFilter .task:not(.due, .scheduled, .process, .start) {
	display: none;
}

.taskido.overdueFilter .year:not([data-types*="overdue"]) {
	display: none;
}

/* .taskido.overdueFilter .details:not([data-types*="overdue"]) {
	display: none;
} */

/* .taskido.overdueFilter .task:not(.overdue) {
	display: none;
} */

/* .taskido.unplannedFilter .year:not([data-types*="unplanned"]) {
	display: none;
}

.taskido.unplannedFilter .details:not([data-types*="unplanned"]) {
	display: none;
} */

.taskido.unplannedFilter .unplanned {
	display: none;
}

```
